### ISSUE TITLE
Manipulator

### ISSUE THREAD

**Issue by strimper13** [chopshop-166/frc-2019#2]
Commands: 
- Pick Up Ball
  - Open Beak: extend solenoid
  - Intake Position: move arms to front limit switches
  - Spin Rollers: actuate motors spinning inward
- Release Ball
  - beak is opened & in intake position
  - spin rollers outward & launch ball
- Pick Up Hatch
  - Close Beak: retract solenoid
  - Fold Back Arms: until hits back limit switch
  - Open Back Beak Once Inside Hatch Panel (Limit): extend solenoids
- Release Hatch:
  - drive to hole (vision), once inside close beak, retract solenoid, back out

Sensors:
HURF
Limit Switches

**Comment by Quinn-5** [comment]
Pick Up Ball:

    Open Beak: extend solenoid
    Intake Position: move arms to front limit switches
    Spin Rollers: actuate motors spinning inward
    Wait for ball to be in position
    Stop rollers
